insert into Groups (Name) values ('Bubbletube');
insert into Groups (Name) values ('Quatz');
insert into Groups (Name) values ('Wikivu');
insert into Groups (Name) values ('Kazio');
insert into Groups (Name) values ('Avavee');
insert into Groups (Name) values ('Jetwire');
insert into Groups (Name) values ('Einti');
insert into Groups (Name) values ('Jayo');
insert into Groups (Name) values ('Yata');
insert into Groups (Name) values ('Mita');

go
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Yanaton', 'Tather', '2005-05-26', 6.0, 5);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Mady', 'Skurm', '2003-09-13', 10.6, 6);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Dukie', 'Fabri', '2005-05-28', 9.0, 2);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Duncan', 'Benthall', '2002-01-10', 5.1, 7);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Cortie', 'Stot', '2006-04-26', 7.8, 9);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Yolanthe', 'Marjoribanks', '1998-01-30', 9.3, 4);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Powell', 'Swindle', '2005-05-30', 6.7, 10);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Les', 'Gash', '2004-01-04', 7.6, 5);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Josefa', 'Haydock', '2002-07-30', 9.0, 8);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Leicester', 'Willshaw', '1997-10-08', 11.1, 4);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Noreen', 'Balderstone', '2000-01-17', 8.1, 2);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Jereme', 'Mayoral', '2004-12-12', 5.4, 6);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Bronnie', 'Dulany', '2002-01-03', 10.1, 6);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Maryrose', 'Thickins', '2005-09-30', 10.0, 4);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Odey', 'Ayars', '1996-10-07', 5.0, 3);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Adrianne', 'Prime', '2002-05-31', 9.0, 1);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Burlie', 'Cropp', '2007-06-05', 6.0, 1);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Case', 'Maha', '1999-08-06', 5.5, 7);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Casar', 'Kordes', '1998-12-28', 10.9, 9);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Rutherford', 'Waker', '2002-02-04', 8.7, 8);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Webb', 'Megahey', '2005-10-27', 8.5, 7);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Gifford', 'Radnedge', '2002-03-02', 6.4, 3);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Judon', 'Heffernon', '2007-06-11', 11.9, 3);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Adara', 'Aubury', '1999-02-07', 11.3, 2);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Garvey', 'Coker', '1999-11-04', 9.9, 8);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Paton', 'O''Doireidh', '1996-09-19', 11.2, 1);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Devin', 'Pedrocco', '2002-10-08', 11.8, 9);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Haskel', 'Nutley', '1999-09-01', 7.6, 9);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Cy', 'Dartnell', '2002-09-28', 8.5, 3);
insert into Students (FirstName, LastName, Birthdate, AverageMark, GroupId) values ('Jaine', 'Davley', '2001-11-22', 8.6, 10);